### ISSUE TITLE
Failed to run process: diskutil apfs resizeContainer disk0s2 468999733248

### ISSUE THREAD

**Issue by tomlube** [AsahiLinux/asahi-installer#115]
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/9135770/installer.log)

The container /dev/disk0s2 appears to be OK
Storage system check exit code is 0
Shrinking APFS Physical Store disk0s2 from 494,384,795,648 to 468,999,733,248 bytes
Shrinking APFS data structures
APFS Container Resize error code is 49187
Error: -69606: A problem occurred while resizing APFS Container structures
Failed to run process: diskutil apfs resizeContainer disk0s2 468999733248
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 852, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 704, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 824, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 635, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '468999733248']' returned non-zero exit status 1.

**Comment by tomlube** [comment]
Currently on Ventura Version 13.0 Beta (22A5295i)

**Comment by marcan** [comment]
Well, that's a new one. This is an Apple APFS bug/corruption issue. Please run First Aid from recovery mode and see if that fixes it. If it doesn't, please file a feedback with Apple.

This one is particularly scary because it happened midway through the resize, not during the prior check... I hope your data is okay! There really isn't anything we can do here, we're just using Apple's resize tool as it was meant to be used, so any problems here are on their side.

It seems every day more people show up with interesting APFS failure cases... I'm still amazed Apple are shipping this filesystem.

**Comment by tomlube** [comment]
Somehow managed to steamroll my way through this, First Aid wasn't very helpful but I got it installed. Now I have this:

U-Boot 2022.04-rc4 (Mar 19 2022 - 14:41:10 +0000) 

Model: Apple MacBook Air (M1, 2020) 

starting USB... 

Bus usb0382280000: Register 200047f NbrPorts 2 

Starting the controller USB XHCI 1.10 

Bus usbe502280000: Register 200047f NbrPorts 2 

Starting the controller USB XHCI 1.10 

scanning bus usb0382280000 for devices.. 1 USB Device(s) found 

scanning bus usb@502280000 for devices. 1 USB Device(s) found 

scanning usb for storage devices... 0 Storage Device(s) found

Hit any key to stop autoboot: 0 

Device 0: unknown device 

Failed to boot from ESP with UUID b3296484-9112-4965-bf91-9157b35ad4e0 

Trying to boot from USB...

Device 0: unknown device 

Failed to find boot partition run `distro_bootcmd` to boot from any partition

**Comment by marcan** [comment]
Argh, I knew I forgot to do something when I pushed the release yesterday... the production installer was still using the old OS images :(

Can you follow the instructions [here](https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet) to delete the install and install again? I just fixed it...

**Comment by tomlube** [comment]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/4616948/179651280-a50adfd2-7bb5-4402-9ff3-605780b7b83b.png">
