### ISSUE TITLE
Failed to install on external drive

### ISSUE THREAD

**Issue by evansan** [AsahiLinux/asahi-installer#163]
I chose wipe and install on my 250GB external drive, but the installer says there is not enough storage.

```
~❯ curl https://alx.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1511  100  1511    0     0   3549      0 --:--:-- --:--:-- --:--:--  3606

Bootstrapping installer:
  Checking version...
  Version: v0.5
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.

Welcome to the Asahi Linux installer!

This installer is in an alpha state, and may not work for everyone.
It is intended for developers and early adopters who are comfortable
debugging issues or providing detailed bug reports.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.


By default, this installer will hide certain advanced options that
are only useful for Asahi Linux developers. You can enable expert mode
to show them. Do not enable this unless you know what you are doing.
Please do not file bugs if things go wrong in expert mode.
» Enable expert mode? (y/N): Y

Collecting system information...
  Product name: MacBook Pro (14-inch, 2021)
  SoC: Apple M1 Pro
  Device class: j314sap
  Product type: MacBookPro18,3
  Board ID: 0x8
  Chip ID: 0x6000
  System firmware: iBoot-8419.41.10
  Boot UUID: 41E02DA9-E558-49B1-876B-588DBAC16C4C
  Boot VGID: 41E02DA9-E558-49B1-876B-588DBAC16C4C
  Default boot VGID: 41E02DA9-E558-49B1-876B-588DBAC16C4C
  Boot mode: macOS
  OS version: 13.0.1 (22A400)
  SFR version: 22.1.400.0.0,0
  System rOS version: 13.0.1 (22A400)
  No Fallback rOS
  Login user: alex

Collecting partition information...
  System disk: disk0
  Found 1 external disk(s)

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (494.38 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v13.0.1 [disk3s1s1, 41E02DA9-E558-49B1-876B-588DBAC16C4C]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v13.0.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  d: Select another disk for installation
  q: Quit without doing anything
» Action (r): d


Choose a disk:
  1: Internal storage
  2: Sabrent Media (256.06 GB)
» Disk: 2

Collecting partition information...
  System disk: disk0
  Found 1 external disk(s)

Collecting OS information...

Partitions in external disk (disk4):
  0: EFI (209.72 MB)
  1: APFS [Sabrent USB NVMe] (255.85 GB, 1 volume)

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  w: Wipe and install into the whole disk
  d: Select another disk for installation
  q: Quit without doing anything
» Action (r): w

This will wipe all data on the currently selected disk.
Are you sure you want to continue?
» Wipe my disk (y/N): Y

Choose an OS to install:
  1: Tethered boot (m1n1, for development)
» OS: 
Enter one of the following: 1
» OS: 
Enter one of the following: 1
» OS: 
Enter one of the following: 1
» OS: 1


Minimum required space for this OS: 2.50 GB

Enter a name for your OS
» OS name (m1n1 proxy): 

Choose the macOS version to use for boot firmware:
(If unsure, just press enter)
  1: 12.4
  2: 13.0
  3: 12.3
» Version (3): 2

Using macOS 13.0 for OS firmware

Downloading macOS OS package info...
- 

Partitioning the whole disk (disk4)
Creating new stub macOS named m1n1 proxy
Installing stub macOS into disk4s1 (m1n1 proxy)
Preparing target volumes...
Checking volumes...
Beginning stub OS install...
| 
Setting up System volume...

Setting up Data volume...
Setting up Preboot volume...
\ 100.00% 
\ root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1046, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 857, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1021, in main_loop
    return self.action_wipe()
  File "/private/tmp/asahi-install/main.py", line 262, in action_wipe
    self.do_install(os_size)
  File "/private/tmp/asahi-install/main.py", line 409, in do_install
    self.ins.install_files(self.cur_os)
  File "/private/tmp/asahi-install/stub.py", line 255, in install_files
    self.extract(path, restore_bundle)
  File "/private/tmp/asahi-install/util.py", line 138, in extract
    self.pkg.extract(src, dest)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1616, in extract
    return self._extract_member(member, path, pwd)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1688, in _extract_member
    shutil.copyfileobj(source, target)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
OSError: [Errno 28] No space left on device
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log

```

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/10143612/installer.log)

**Comment by marcan** [comment]
I need to log file to figure out what happened.

Note that the external install stuff only works for m1n1 only and is only for demo purposes. It is not useful to anyone but a tiny subset of developers.

**Comment by marcan** [comment]
macOS 13.0 is on the list only for experimentation purposes. It's probably too large for the current APFS stub partition sizes.

Both 13.0 and the external install feature are only there for developers and not useful to end users, so I'm going to close this since it is not a supported operation. Expert mode is expected to break if you don't know what you're doing. We'll cross these bridges when we get there.
