### ISSUE TITLE
Error: -69822: Couldn't rediscover disk after operation

### ISSUE THREAD

**Issue by wblondel** [AsahiLinux/asahi-installer#184]
Hello,

I resized, using the installer, my MacOS volume to have 100GB free space. I had to reboot for the installer to see it.
But now it isn't able to create a new partition in this free space:

```
Downloading macOS OS package info...
- 

Creating new stub macOS named Asahi Linux
Failed to run process: diskutil addPartition disk0s2 apfs 'Asahi Linux' 2499805184
Output: b"The new partition to be added will be of a filesystem personality of APFS apfs APFS 7C3457EF-0000-11AA-AA11-00306543ECAC\nThe new partition will be added following disk0s2\nStarted partitioning on disk0\nModification de la carte de partition\nError: -69822: Couldn't rediscover disk after operation\n"
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1054, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 865, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1017, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 305, in action_install_into_free
    self.part = self.dutil.addPartition(free_part.name, "apfs", self.osins.name, STUB_SIZE)
  File "/private/tmp/asahi-install/diskutil.py", line 250, in addPartition
    self.action("addPartition", after, fs, label, size, verbose=True)
  File "/private/tmp/asahi-install/diskutil.py", line 34, in action
    p = subprocess.run(["diskutil"] + list(args), check=True,
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'addPartition', 'disk0s2', 'apfs', 'Asahi Linux', '2499805184']' returned non-zero exit status 1.
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
```

I tried twice to make sure, same issue
What would be the cause?

Thank you

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/11129734/installer.log)

**Comment by wblondel** [comment]
Hi,

I found the cause of the issue. An Acronis backup was ongoing when I ran the installer. I stopped it and tried again, and it worked.
