### ISSUE TITLE
Installer fails to install Fedora Rawhide

### ISSUE THREAD

**Issue by dupontinquiries** [AsahiLinux/asahi-installer#216]
I tried installing a new fedora rawhide install today and the installer crashed with the following traceback:

```
Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (150.00 GB, 7 volumes)
    OS: [B ] [Macintosh HD] macOS v13.5.1 [disk4s3s1, 7D3DA174-F7CC-48B0-BCC8-E06422151CF0]
  2: (free space: 48.93 GB)
  3: APFS [big-silicon-asahi] (2.50 GB, 4 volumes)
    OS: [ *] [big-silicon-asahi] m1n1 v1.3.3 (macOS 12.3 stub) [disk2s2, 3C8221E6-BE1B-44A3-B675-569695E02160]
  4: EFI (500.17 MB)
  5: Linux Filesystem (792.73 GB)
  6: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v13.5.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk4s3s1) for machine authentication.

Choose what to do:
  f: Install an OS into free space
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (f): f

Choose an OS to install:
  1: Fedora Linux 38 with KDE Plasma (202310041600)
  2: Fedora Linux 38 with KDE Plasma (202310031600)
  3: Fedora Linux 38 with KDE Plasma (202310021600)
  4: Fedora Linux 38 with GNOME (202310041600)
  5: Fedora Linux 38 with GNOME (202310031600)
  6: Fedora Linux 38 with GNOME (202310021600)
  7: Fedora Linux 38 Server (202310041600)
  8: Fedora Linux 38 Server (202310031600)
  9: Fedora Linux 38 Server (202310021600)
  10: Fedora Linux 38 Minimal (202310041600)
  11: Fedora Linux 38 Minimal (202310031600)
  12: Fedora Linux 38 Minimal (202310021600)
  13: Fedora Linux 39 with KDE Plasma (202310041600)
  14: Fedora Linux 39 with KDE Plasma (202310031600)
  15: Fedora Linux 39 with KDE Plasma (202310021600)
  16: Fedora Linux 39 with GNOME (202310041600)
  17: Fedora Linux 39 with GNOME (202310031600)
  18: Fedora Linux 39 with GNOME (202310021600)
  19: Fedora Linux 39 Server (202310041600)
  20: Fedora Linux 39 Server (202310031600)
  21: Fedora Linux 39 Server (202310021600)
  22: Fedora Linux 39 Minimal (202310041600)
  23: Fedora Linux 39 Minimal (202310031600)
  24: Fedora Linux 39 Minimal (202310021600)
  25: Fedora Linux Rawhide with KDE Plasma (202310031600)
  26: Fedora Linux Rawhide with KDE Plasma (202310021600)
  27: Fedora Linux Rawhide with KDE Plasma (202310011600)
  28: Fedora Linux Rawhide with GNOME (202310031600)
  29: Fedora Linux Rawhide with GNOME (202310021600)
  30: Fedora Linux Rawhide with GNOME (202310011600)
  31: Fedora Linux Rawhide Server (202310031600)
  32: Fedora Linux Rawhide Server (202310021600)
  33: Fedora Linux Rawhide Server (202310011600)
  34: Fedora Linux Rawhide Minimal (202310031600)
  35: Fedora Linux Rawhide Minimal (202310021600)
  36: Fedora Linux Rawhide Minimal (202310011600)
» OS: 25

Downloading OS package info...
- 

Minimum required space for this OS: 17.07 GB

Available free space: 48.93 GB

How much space should be allocated to the new OS?
  You can enter a size such as '1GB', a fraction such as '50%',
  the word 'min' for the smallest allowable size, or
  the word 'max' to use all available space.
» New OS size (max): max

The new OS will be allocated 48.93 GB of space,
leaving 0 B of free space.

Enter a name for your OS
» OS name (Fedora Linux with KDE Plasma): fedora-rawhide

Using macOS 13.5 for OS firmware

Downloading macOS OS package info...
- 

Creating new stub macOS named fedora-rawhide
Installing stub macOS into disk0s8 (fedora-rawhide)
Preparing target volumes...
Checking volumes...
Beginning stub OS install...
| 
Setting up System volume...

Setting up Data volume...
Setting up Preboot volume...
/ 100.00% (0.00 B/s)
Setting up Recovery volume...
\ 100.00% (6.63 MB/s)
Wrapping up...

Stub OS installation complete.

Adding partition EFI (524.29 MB)...
  Formatting as FAT...
Adding partition Boot (1.05 GB)...
Adding partition Root (44.86 GB)...
Collecting firmware...
Installing OS...
\ 100.00% (0.00 B/s)
  Copying from esp into disk0s9 partition...
| 100.00% (0.00 B/s)
  Copying firmware into disk0s9 partition...
  Extracting boot.img into disk0s10 partition...
\ 100.00% (7.99 MB/s)
  Extracting root.img into disk0s11 partition...
\ 100.00% (8.54 MB/s))
Downloading extra files...
  Downloading  (1/1)...
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1050, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 858, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1013, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 320, in action_install_into_free
    self.do_install(os_size)
  File "/private/tmp/asahi-install/main.py", line 440, in do_install
    self.osins.install(self.ins)
  File "/private/tmp/asahi-install/osinstall.py", line 162, in install
    self.download_extras()
  File "/private/tmp/asahi-install/osinstall.py", line 113, in download_extras
    ucache = urlcache.URLCache(url)
  File "/private/tmp/asahi-install/urlcache.py", line 26, in __init__
    self.size = self.get_size()
  File "/private/tmp/asahi-install/urlcache.py", line 66, in get_size
    con = self.get_con()
  File "/private/tmp/asahi-install/urlcache.py", line 57, in get_con
    raise Exception(f"Unsupported scheme {self.url.scheme}")
Exception: Unsupported scheme 
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
```

I have attached the log as well.
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/12821115/installer.log)

Please let me know if I should submit any other information.

**Comment by dupontinquiries** [comment]
I traced it back to some link being in https. I assume it should be in http in order to be supported?

**Comment by chicknwinner** [comment]
had this problem and in 

installer_data.json

i replaced

"extras": [""]

with

"extras": {}

for the rawhide entries and it seemed to work (just based on. the fact that is what it is for other entries which work)

**Comment by marcan** [comment]
This is a problem with the Fedora installer configs, which I believe should be fixed now (but you might have to wait for the next image build run).

https://pagure.io/fedora-asahi/kiwi-descriptions/pull-request/43

**Comment by jannau** [comment]
Whenever that will be. Image generation for rawhide is currently broken. After it is fixed rawhide images will require expert mode and should not be used except for test systems.
