### ISSUE TITLE
Unable to install Asahi Ubuntu on M1 MacBook Air

### ISSUE THREAD

**Issue by JoshAtticus** [AsahiLinux/asahi-installer#228]
This is the error I encounter

```
josh@Joshs-Air ~ % curl -sL https://ubuntuasahi.org/install | bash
Bootstrapping installer:
  Checking version...
  Version: v0.6.14
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1049, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 106, in __init__
    self.data = json.load(open("installer_data.json"))
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log

```
Upon opening the installer.log file, it shows this

```
josh@Joshs-Air ~ % cat /private/tmp/asahi-install/installer.log
10-27 12:14 root         INFO     Startup
10-27 12:14 root         INFO     Environment:
10-27 12:14 root         INFO       INSTALLER_BASE=https://cdn.asahilinux.org/installer
10-27 12:14 root         INFO       INSTALLER_DATA=https://tobhe.de/ubuntu/installer_data.json
10-27 12:14 root         INFO       REPO_BASE=https://files.tobhe.de/ubuntu
10-27 12:14 root         INFO       IPSW_BASE=None
10-27 12:14 root         INFO       EXPERT=None
10-27 12:14 root         INFO       REPORT=None
10-27 12:14 root         INFO       REPORT_TAG=None
10-27 12:14 root         INFO     Version: v0.6.14
10-27 12:14 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1049, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 106, in __init__
    self.data = json.load(open("installer_data.json"))
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
10-27 12:14 root         INFO     MSG: If you need to file a bug report, please attach the log file:
10-27 12:14 root         INFO     MSG:   /private/tmp/asahi-install/installer.log
josh@Joshs-Air ~ % 

```

**Comment by liberodark** [comment]
You probably need to ask the project directly : https://github.com/UbuntuAsahi/ubuntu-asahi
Because you have installer issue not asahi issue.

Best Regards

**Comment by JoshAtticus** [comment]
> You probably need to ask the project directly : https://github.com/UbuntuAsahi/ubuntu-asahi Because you have installer issue not asahi issue.
> 
> Best Regards

Have done that, thank you!

**Comment by eslerm** [comment]
Looks like the installer issue was worked out https://github.com/UbuntuAsahi/ubuntu-asahi/issues/68

**Comment by JoshAtticus** [comment]
> Looks like the installer issue was worked out [UbuntuAsahi/ubuntu-asahi#68](https://github.com/UbuntuAsahi/ubuntu-asahi/issues/68)

It wasn't worked out I just forgot to try and reinstall

**Comment by JoshAtticus** [comment]
> i have the same issue did this ever get resolved
Yes for me at least

**Comment by k3nmaru** [comment]
asahi fedora is unable to install on my m1 macbook air . ubuntu asahi installed but many errors in it. are they same or asahi fedora is better ?

**Comment by eslerm** [comment]
@k3nmaru your install issues do not sound related to this thread.

Before posting a new issue, I recommend a macOS reinstall to make sure you are starting from a clean slate. That might sound extreme, but will likely resolve your problem.

If install issues persist after reinstalling macOS, please take a screenshot or text of the errors and file a new issue.

**Comment by k3nmaru** [comment]
> @k3nmaru your install issues do not sound related to this thread.
> 
> Before posting a new issue, I recommend a macOS reinstall to make sure you are starting from a clean slate. That might sound extreme, but will likely resolve your problem.
> 
> If install issues persist after reinstalling macOS, please take a screenshot or text of the errors and file a new issue.

Just reinstalled it. That's why asking . Recommend the thread where i can ask these questions.

**Comment by jzqsss** [comment]
exactly the same error

**Comment by para9oid** [comment]
> exactly the same error

Use vpn
