### ISSUE TITLE
Installer error: Collecting system information fails

### ISSUE THREAD

**Issue by raresNagy** [AsahiLinux/asahi-installer#257]
Installer can't get past Collecting system information, python errors out
```
log
02-27 12:29 root         INFO     Startup
02-27 12:29 root         INFO     Environment:
02-27 12:29 root         INFO       INSTALLER_BASE=https://cdn.asahilinux.org/installer
02-27 12:29 root         INFO       INSTALLER_DATA=https://github.com/AsahiLinux/asahi-installer/raw/prod/data/installer_data.json
02-27 12:29 root         INFO       REPO_BASE=https://cdn.asahilinux.org
02-27 12:29 root         INFO       IPSW_BASE=None
02-27 12:29 root         INFO       EXPERT=None
02-27 12:29 root         INFO       REPORT=https://stats.asahilinux.org/report
02-27 12:29 root         INFO       REPORT_TAG=alx-prod
02-27 12:29 root         INFO     Version: v0.7.1
02-27 12:29 root         INFO     MSG: Welcome to the Asahi Linux installer!
02-27 12:29 root         INFO     MSG: This installer will guide you through the process of setting up
02-27 12:29 root         INFO     MSG: Asahi Linux on your Mac.
02-27 12:29 root         INFO     MSG: Please make sure you are familiar with our documentation at:
02-27 12:29 root         INFO     MSG:   https://alx.sh/w
02-27 12:29 root         INFO     MSG: Press enter to continue.
02-27 12:30 root         INFO     MSG: Collecting system information...
02-27 12:30 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1058, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 831, in main
    self.sysinfo = system.SystemInfo()
  File "/private/tmp/asahi-install/system.py", line 8, in __init__
    self.fetch()
  File "/private/tmp/asahi-install/system.py", line 18, in fetch
    self.ioservice = plistlib.loads(result.stdout)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 883, in loads
    return load(fp, fmt=fmt, dict_type=dict_type)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 875, in load
    return p.parse(fp)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 177, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 305930, column 38
02-27 12:30 root         INFO     MSG: If you need to file a bug report, please attach the log file:
02-27 12:30 root         INFO     MSG:   /private/tmp/asahi-install/installer.log
```

**Comment by raresNagy** [comment]
The problem seemed to have solved itself, all I did was wait a few hours and try again. I'm leaving this open if maybe someone can find a potential cause

**Comment by eslerm** [comment]
This looks like https://github.com/AsahiLinux/asahi-installer/issues/251

Did you have an additional display plugged in during the initial install?

**Comment by eslerm** [comment]
No worries @raresNagy

Thanks for verifying the cause!
