### ISSUE TITLE
Installer Exits: No actions available on this system

### ISSUE THREAD

**Issue by ezfe** [AsahiLinux/asahi-installer#28]
The installer exited with the message "No actions available on this system". I know I don't have enough free space to install but would expect it to say that if that's what the issue is here.

```
03-18 20:48 root         INFO     Startup
03-18 20:48 root         INFO     Environment:
03-18 20:48 root         INFO       INSTALLER_BASE=https://cdn.asahilinux.org/installer
03-18 20:48 root         INFO       INSTALLER_DATA=https://github.com/AsahiLinux/asahi-installer/raw/prod/data/installer_data.json
03-18 20:48 root         INFO       REPO_BASE=https://cdn.asahilinux.org
03-18 20:48 root         INFO       IPSW_BASE=None
03-18 20:48 root         INFO     Version: v0.3.2

03-18 20:48 root         INFO     MSG: Welcome to the Asahi Linux installer!
03-18 20:48 root         INFO     MSG: This installer is in an alpha state, and may not work for everyone.
03-18 20:48 root         INFO     MSG: It is intended for developers and early adopters who are comfortable
03-18 20:48 root         INFO     MSG: debugging issues or providing detailed bug reports.
03-18 20:48 root         INFO     MSG: Please make sure you are familiar with our documentation at:
03-18 20:48 root         INFO     MSG:   [34;1mhttps://alx.sh/w[m[m
03-18 20:48 root         INFO     MSG: Press enter to continue.
03-18 20:50 root         INFO     MSG: By default, this installer will hide certain advanced options that
03-18 20:50 root         INFO     MSG: are only useful for developers. You can enable expert mode to show them.
03-18 20:50 root         INFO     MSG: [1;37m»[1;36m Enable expert mode? (y/N): [m
03-18 20:50 root         INFO     INPUT: 'n'
03-18 20:50 root         INFO     MSG: Collecting system information...
03-18 20:50 root         INFO     MSG:   Product name: [mMacBook Air (M1, 2020)[m
03-18 20:50 root         INFO     MSG:   SoC: [mApple M1[m
03-18 20:50 root         INFO     MSG:   Device class: [mj313ap[m
03-18 20:50 root         INFO     MSG:   Product type: [mMacBookAir10,1[m
03-18 20:50 root         INFO     MSG:   Board ID: [m0x26[m
03-18 20:50 root         INFO     MSG:   Chip ID: [m0x8103[m
03-18 20:50 root         INFO     MSG:   System firmware: [miBoot-7459.101.2[m
03-18 20:50 root         INFO     MSG:   Boot UUID: [m8D1477E6-A375-41B8-A696-3451DE48160A[m
03-18 20:50 root         INFO     MSG:   Boot VGID: [m8D1477E6-A375-41B8-A696-3451DE48160A[m
03-18 20:50 root         INFO     MSG:   Default boot VGID: [m8D1477E6-A375-41B8-A696-3451DE48160A[m
03-18 20:50 root         INFO     MSG:   Boot mode: [mmacOS[m
03-18 20:50 root         INFO     MSG:   OS version: [m12.3 (21E230)[m
03-18 20:50 root         INFO     MSG:   System rOS version: [m12.3 (21E230)[m
03-18 20:50 root         INFO     MSG:   No Fallback rOS
03-18 20:50 root         INFO     MSG:   Login user: [mezekielelin[m
03-18 20:50 root         INFO     MSG: Collecting partition information...
03-18 20:50 root         INFO     DiskUtil.get_info()
03-18 20:50 root         INFO     DiskUtil.get_list()
03-18 20:50 root         DEBUG    get: diskutil ('list', '-plist')
03-18 20:50 root         INFO     DiskUtil.get_apfs_list()
03-18 20:50 root         DEBUG    get: diskutil ('apfs', 'list', '-plist')
03-18 20:50 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk1', '-plist')
03-18 20:50 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk2', '-plist')
03-18 20:50 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk3', '-plist')
03-18 20:50 root         INFO     DiskUtil.get_disk_info()
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk0')
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk1')
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk2')
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk3')
03-18 20:50 root         INFO     DiskUtil.find_system_disk()
03-18 20:50 root         INFO     System disk: disk0
03-18 20:50 root         INFO     MSG:   System disk: [mdisk0[m
03-18 20:50 root         INFO     DiskUtil.get_partitions('disk0')
03-18 20:50 root         INFO     DiskUtil.get_partition_info(dev='disk0s1', refresh_apfs=False)
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s1')
03-18 20:50 root         INFO     DiskUtil.get_partition_info(dev='disk0s2', refresh_apfs=False)
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s2')
03-18 20:50 root         INFO     DiskUtil.get_partition_info(dev='disk0s3', refresh_apfs=False)
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s3')
03-18 20:50 root         INFO     MSG: Collecting OS information...
03-18 20:50 root         INFO     OSEnum.collect()
03-18 20:50 root         INFO     OSEnum.collect_part(part=disk0s1)
03-18 20:50 root         INFO     OSEnum.collect_part(part=disk0s2)
03-18 20:50 root         INFO     OSEnum.collect_os(part=disk0s2, vgid=8D1477E6-A375-41B8-A696-3451DE48160A)
03-18 20:50 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk3s2')
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk3s2')
03-18 20:50 root         INFO       mounts[Preboot]: /System/Volumes/Preboot
03-18 20:50 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk3s3')
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk3s3')
03-18 20:50 root         INFO       mounts[Recovery]: /Volumes/Recovery
03-18 20:50 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk3s1')
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk3s1')
03-18 20:50 root         INFO       mounts[System]: /Volumes/Macintosh HD 1
03-18 20:50 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk3s5')
03-18 20:50 root         DEBUG    get: diskutil ('info', '-plist', 'disk3s5')
03-18 20:50 root         INFO       mounts[Data]: /System/Volumes/Data
03-18 20:50 root         INFO       Trying SystemVersion.plist...
03-18 20:50 root         INFO         Version: 12.3
03-18 20:50 root         INFO       Trying SystemVersion-disabled.plist...
03-18 20:50 root         INFO         Not Found
03-18 20:50 root         INFO       Admin users: ['ezekielelin', 'sydney']
03-18 20:50 root         INFO       BootPolicy[coih] = None
03-18 20:50 root         INFO       BootPolicy[nsih] = 3393238C1FD84CEEB63BD0EE574041838499DC92C2825975EDA42B7793C8DE125745EC62ABDD515D3EFF948DD327C235
03-18 20:50 root         INFO      Found [[1mMacintosh HD[m] [1;32mmacOS v12.3[m [disk3s1, 8D1477E6-A375-41B8-A696-3451DE48160A]
03-18 20:50 root         INFO     OSEnum.collect_recovery(part=disk0s3)
03-18 20:50 root         INFO      Found SROS: recoveryOS v12.3 [Primary recoveryOS]
03-18 20:50 root         INFO     Checking resizability of disk0s2
03-18 20:50 root         INFO       Has OS
03-18 20:50 root         INFO       Min space required: 38500000000
03-18 20:50 root         INFO       Free space: 14744420352
03-18 20:50 root         INFO       Cannot resize
03-18 20:50 root         INFO     Checking resizability of disk0s3
03-18 20:50 root         INFO       Has OS
03-18 20:50 root         INFO       Min space required: 38500000000
03-18 20:50 root         INFO       Free space: 3642916864
03-18 20:50 root         INFO       Cannot resize
03-18 20:50 root         INFO     MSG: Partitions in system disk (disk0):
03-18 20:50 root         INFO     MSG:   [1m1[m: APFS [Macintosh HD] (245.11 GB, 6 volumes)[m
03-18 20:50 root         INFO     MSG:     OS: [[32mB[m[1m*[m] [[1mMacintosh HD[m] [1;32mmacOS v12.3[m [disk3s1, 8D1477E6-A375-41B8-A696-3451DE48160A][m
03-18 20:50 root         INFO     MSG:   [1m2[m: APFS (System Recovery) (5.37 GB, 2 volumes)[m
03-18 20:50 root         INFO     MSG:     OS: [  ] recoveryOS v12.3 [Primary recoveryOS]
03-18 20:50 root         INFO     MSG:   [[32mB[m ] = Booted OS, [[33mR[m ] = Booted recovery, [[31m?[m ] = Unknown[m
03-18 20:50 root         INFO     MSG:   [ [1m*[m] = Default boot volume[m
03-18 20:50 root         INFO     MSG: Using OS 'Macintosh HD' (disk3s1) for machine authentication.
03-18 20:50 root         INFO     Current OS: Macintosh HD / disk3s1
03-18 20:50 root         INFO     MSG: No actions available on this system.
03-18 20:50 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 802, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 654, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 760, in main_loop
    sys.exit(1)
SystemExit: 1
03-18 20:50 root         INFO     MSG: If you need to file a bug report, please attach the log file:
03-18 20:50 root         INFO     MSG:   /private/tmp/asahi-install/installer.log
```

**Comment by one-and-only** [comment]
It does state that there isn't enough space available:
```
03-18 20:50 root         INFO       Min space required: 38500000000
03-18 20:50 root         INFO       Free space: 3642916864
03-18 20:50 root         INFO       Cannot resize
```
