### ISSUE TITLE
xattr -x from -wx unrecognised

### ISSUE THREAD

**Issue by georgeccotea** [AsahiLinux/asahi-installer#30]
03-19 01:48 root         INFO     Startup
03-19 01:48 root         INFO     Environment:
03-19 01:48 root         INFO       INSTALLER_BASE=https://cdn.asahilinux.org/installer
03-19 01:48 root         INFO       INSTALLER_DATA=https://github.com/AsahiLinux/asahi-installer/raw/prod/data/installer_data.json
03-19 01:48 root         INFO       REPO_BASE=https://cdn.asahilinux.org
03-19 01:48 root         INFO       IPSW_BASE=None
03-19 01:48 root         INFO     Version: v0.3.2

03-19 01:48 root         INFO     MSG: Welcome to the Asahi Linux installer!
03-19 01:48 root         INFO     MSG: This installer is in an alpha state, and may not work for everyone.
03-19 01:48 root         INFO     MSG: It is intended for developers and early adopters who are comfortable
03-19 01:48 root         INFO     MSG: debugging issues or providing detailed bug reports.
03-19 01:48 root         INFO     MSG: Please make sure you are familiar with our documentation at:
03-19 01:48 root         INFO     MSG:   [34;1mhttps://alx.sh/w[m[m
03-19 01:48 root         INFO     MSG: Press enter to continue.
03-19 01:48 root         INFO     MSG: By default, this installer will hide certain advanced options that
03-19 01:48 root         INFO     MSG: are only useful for developers. You can enable expert mode to show them.
03-19 01:48 root         INFO     MSG: [1;37m»[1;36m Enable expert mode? (y/N): [m
03-19 01:48 root         INFO     INPUT: 'n'
03-19 01:48 root         INFO     MSG: Collecting system information...
03-19 01:48 root         INFO     MSG:   Product name: [mMacBook Pro (14-inch, 2021)[m
03-19 01:48 root         INFO     MSG:   SoC: [mApple M1 Pro[m
03-19 01:48 root         INFO     MSG:   Device class: [mj314sap[m
03-19 01:48 root         INFO     MSG:   Product type: [mMacBookPro18,3[m
03-19 01:48 root         INFO     MSG:   Board ID: [m0x8[m
03-19 01:48 root         INFO     MSG:   Chip ID: [m0x6000[m
03-19 01:48 root         INFO     MSG:   System firmware: [miBoot-7459.101.2[m
03-19 01:48 root         INFO     MSG:   Boot UUID: [m725C2F4B-1485-4E45-9691-730922778335[m
03-19 01:48 root         INFO     MSG:   Boot VGID: [m725C2F4B-1485-4E45-9691-730922778335[m
03-19 01:48 root         INFO     MSG:   Default boot VGID: [m725C2F4B-1485-4E45-9691-730922778335[m
03-19 01:48 root         INFO     MSG:   Boot mode: [mmacOS[m
03-19 01:48 root         INFO     MSG:   OS version: [m12.3 (21E230)[m
03-19 01:48 root         INFO     MSG:   System rOS version: [m12.3 (21E230)[m
03-19 01:48 root         INFO     MSG:   No Fallback rOS
03-19 01:48 root         INFO     MSG:   Login user: [mgeorge[m
03-19 01:48 root         INFO     MSG: Collecting partition information...
03-19 01:48 root         INFO     DiskUtil.get_info()
03-19 01:48 root         INFO     DiskUtil.get_list()
03-19 01:48 root         DEBUG    get: diskutil ('list', '-plist')
03-19 01:48 root         INFO     DiskUtil.get_apfs_list()
03-19 01:48 root         DEBUG    get: diskutil ('apfs', 'list', '-plist')
03-19 01:48 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk1', '-plist')
03-19 01:48 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk2', '-plist')
03-19 01:48 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk3', '-plist')
03-19 01:48 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk4', '-plist')
03-19 01:48 root         INFO     DiskUtil.get_disk_info()
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk0')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk1')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk2')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk3')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk4')
03-19 01:48 root         INFO     DiskUtil.find_system_disk()
03-19 01:48 root         INFO     System disk: disk0
03-19 01:48 root         INFO     MSG:   System disk: [mdisk0[m
03-19 01:48 root         INFO     DiskUtil.get_partitions('disk0')
03-19 01:48 root         INFO     DiskUtil.get_partition_info(dev='disk0s1', refresh_apfs=False)
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s1')
03-19 01:48 root         INFO     DiskUtil.get_partition_info(dev='disk0s2', refresh_apfs=False)
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s2')
03-19 01:48 root         INFO     DiskUtil.get_partition_info(dev='disk0s5', refresh_apfs=False)
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s5')
03-19 01:48 root         INFO     DiskUtil.get_partition_info(dev='disk0s3', refresh_apfs=False)
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s3')
03-19 01:48 root         INFO     MSG: Collecting OS information...
03-19 01:48 root         INFO     OSEnum.collect()
03-19 01:48 root         INFO     OSEnum.collect_part(part=disk0s1)
03-19 01:48 root         INFO     OSEnum.collect_part(part=disk0s2)
03-19 01:48 root         INFO     OSEnum.collect_os(part=disk0s2, vgid=725C2F4B-1485-4E45-9691-730922778335)
03-19 01:48 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk3s2')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk3s2')
03-19 01:48 root         INFO       mounts[Preboot]: /System/Volumes/Preboot
03-19 01:48 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk3s3')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk3s3')
03-19 01:48 root         INFO       mounts[Recovery]: /Volumes/Recovery
03-19 01:48 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk3s1')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk3s1')
03-19 01:48 root         INFO       mounts[System]: /Volumes/Macintosh HD 1
03-19 01:48 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk3s5')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk3s5')
03-19 01:48 root         INFO       mounts[Data]: /System/Volumes/Data
03-19 01:48 root         INFO       Trying SystemVersion.plist...
03-19 01:48 root         INFO         Version: 12.3
03-19 01:48 root         INFO       Trying SystemVersion-disabled.plist...
03-19 01:48 root         INFO         Not Found
03-19 01:48 root         INFO       Admin users: ['george']
03-19 01:48 root         INFO       BootPolicy[coih] = None
03-19 01:48 root         INFO       BootPolicy[nsih] = 316AEC9549F8956A002659EB1582D46CA7FF83BA4BEEF3A968A4E20B52851FECB33ECA61596DEF043BB9A83A1190AB4C
03-19 01:48 root         INFO      Found [[1mMacintosh HD[m] [1;32mmacOS v12.3[m [disk3s1, 725C2F4B-1485-4E45-9691-730922778335]
03-19 01:48 root         INFO     OSEnum.collect_part(part=disk0s5)
03-19 01:48 root         INFO     OSEnum.collect_os(part=disk0s5, vgid=915AA9DD-8BB5-426E-BC90-37E7062FEDEB)
03-19 01:48 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk4s3')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk4s3')
03-19 01:48 root         INFO       mounts[Preboot]: /Volumes/Preboot
03-19 01:48 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk4s4')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk4s4')
03-19 01:48 root         INFO       mounts[Recovery]: /Volumes/Recovery 1
03-19 01:48 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk4s2')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk4s2')
03-19 01:48 root         INFO       mounts[System]: /Volumes/Asahi Linux
03-19 01:48 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk4s1')
03-19 01:48 root         DEBUG    get: diskutil ('info', '-plist', 'disk4s1')
03-19 01:48 root         INFO       mounts[Data]: /Volumes/Asahi Linux - Data
03-19 01:48 root         INFO       Trying SystemVersion.plist...
03-19 01:48 root         INFO         Not Found
03-19 01:48 root         INFO       Trying SystemVersion-disabled.plist...
03-19 01:48 root         INFO         Not Found
03-19 01:48 root         WARNING    Failed to get AdminUserRecoveryInfo.plist
03-19 01:48 root         WARNING    bputil failed
03-19 01:48 root         INFO      Found [[1mAsahi Linux[m] [1;31mincomplete install[m (macOS None stub) [disk4s2, 915AA9DD-8BB5-426E-BC90-37E7062FEDEB]
03-19 01:48 root         INFO     OSEnum.collect_part(part=disk0s5)
03-19 01:48 root         INFO     OSEnum.collect_recovery(part=disk0s3)
03-19 01:48 root         INFO      Found SROS: recoveryOS v12.3 [Primary recoveryOS]
03-19 01:48 root         INFO     Checking resizability of disk0s2
03-19 01:48 root         INFO       Has OS
03-19 01:48 root         INFO       Min space required: 38500000000
03-19 01:48 root         INFO       Free space: 143627816960
03-19 01:48 root         INFO       Can resize
03-19 01:48 root         INFO     Checking resizability of disk0s5
03-19 01:48 root         INFO       Min space required: 1500000000
03-19 01:48 root         INFO       Free space: 2488578048
03-19 01:48 root         INFO       Can resize
03-19 01:48 root         INFO     Checking resizability of disk0s3
03-19 01:48 root         INFO       Has OS
03-19 01:48 root         INFO       Min space required: 38500000000
03-19 01:48 root         INFO       Free space: 3639705600
03-19 01:48 root         INFO       Cannot resize
03-19 01:48 root         INFO     MSG: Partitions in system disk (disk0):
03-19 01:48 root         INFO     MSG:   [1m1[m: APFS [Macintosh HD] (395.51 GB, 6 volumes)[m
03-19 01:48 root         INFO     MSG:     OS: [[32mB[m[1m*[m] [[1mMacintosh HD[m] [1;32mmacOS v12.3[m [disk3s1, 725C2F4B-1485-4E45-9691-730922778335][m
03-19 01:48 root         INFO     MSG:   [1m2[m: APFS [Asahi Linux] (2.50 GB, 4 volumes)[m
03-19 01:48 root         INFO     MSG:   [1m3[m: (free space: 96.38 GB)[m
03-19 01:48 root         INFO     MSG:   [1m4[m: APFS (System Recovery) (5.37 GB, 2 volumes)[m
03-19 01:48 root         INFO     MSG:     OS: [  ] recoveryOS v12.3 [Primary recoveryOS]
03-19 01:48 root         INFO     MSG:   [[32mB[m ] = Booted OS, [[33mR[m ] = Booted recovery, [[31m?[m ] = Unknown[m
03-19 01:48 root         INFO     MSG:   [ [1m*[m] = Default boot volume[m
03-19 01:48 root         INFO     MSG: Using OS 'Macintosh HD' (disk3s1) for machine authentication.
03-19 01:48 root         INFO     Current OS: Macintosh HD / disk3s1
03-19 01:48 root         INFO     MSG: Choose what to do:
03-19 01:48 root         INFO     MSG:   [1mf[22m: Install an OS into free space[m
03-19 01:48 root         INFO     MSG:   [1mr[22m: Resize an existing partition to make space for a new OS[m
03-19 01:48 root         INFO     MSG:   [1mq[22m: Quit without doing anything[m
03-19 01:48 root         INFO     MSG: [1;37m»[1;36m Action (f): [m
03-19 01:48 root         INFO     INPUT: 'f'
03-19 01:48 root         INFO     MSG: Choose an OS to install:
03-19 01:48 root         INFO     MSG:   [1m1[22m: Asahi Linux Desktop[m
03-19 01:48 root         INFO     MSG:   [1m2[22m: Asahi Linux Minimal (Arch Linux ARM)[m
03-19 01:48 root         INFO     MSG:   [1m3[22m: UEFI environment only (m1n1 + U-Boot + ESP)[m
03-19 01:48 root         INFO     MSG: [1;37m»[1;36m OS: [m
03-19 01:49 root         INFO     INPUT: '1'
03-19 01:49 root         INFO     Chosen OS: Asahi Linux Desktop
03-19 01:49 root         INFO     OS package URL: https://cdn.asahilinux.org/os/asahi-plasma-20220318-2.zip
03-19 01:49 root         INFO     MSG: Downloading OS package info...
03-19 01:49 root         INFO     OS package opened
03-19 01:49 root         INFO     MSG: Minimum required space for this OS: 15.00 GB
03-19 01:49 root         INFO     MSG: Available free space: 96.38 GB
03-19 01:49 root         INFO     MSG: How much space should be allocated to the new OS?
03-19 01:49 root         INFO     MSG:   You can enter a size such as '1GB', a fraction such as '50%',
03-19 01:49 root         INFO     MSG:   the word 'min' for the smallest allowable size, or
03-19 01:49 root         INFO     MSG:   the word 'max' to use all available space.
03-19 01:49 root         INFO     MSG: [1;37m»[1;36m New OS size (max): [m
03-19 01:49 root         INFO     INPUT: 'max'
03-19 01:49 root         INFO     MSG: The new OS will be allocated 96.38 GB of space,
03-19 01:49 root         INFO     MSG: leaving 86.02 KB of free space.
03-19 01:49 root         INFO     MSG: Enter a name for your OS
03-19 01:49 root         INFO     MSG: [1;37m»[1;36m OS name (Asahi Linux): [m
03-19 01:49 root         INFO     INPUT: 'Asahi'
03-19 01:49 root         INFO     New OS name: Asahi
03-19 01:49 root         INFO     MSG: Using macOS 12.3 for OS firmware
03-19 01:49 root         INFO     Chosen IPSW version: 12.3
03-19 01:49 root         INFO     IPSW URL: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/071-08757/74A4F2A1-C747-43F9-A22A-C0AD5FB4ECB6/UniversalMac_12.3_21E230_Restore.ipsw
03-19 01:49 root         INFO     MSG: Downloading macOS OS package info...
03-19 01:49 root         INFO     OS package opened
03-19 01:49 root         INFO     MSG: Creating new stub macOS named Asahi
03-19 01:49 root         INFO     Creating stub macOS: Asahi
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'addPartition', 'disk0s5', 'apfs', 'Asahi', '2499805184')
03-19 01:49 root         INFO     DiskUtil.get_list()
03-19 01:49 root         DEBUG    get: diskutil ('list', '-plist')
03-19 01:49 root         INFO     DiskUtil.get_partitions('disk0')
03-19 01:49 root         INFO     DiskUtil.get_partition_info(dev='disk0s1', refresh_apfs=False)
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s1')
03-19 01:49 root         INFO     DiskUtil.get_partition_info(dev='disk0s2', refresh_apfs=False)
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s2')
03-19 01:49 root         INFO     DiskUtil.get_partition_info(dev='disk0s5', refresh_apfs=False)
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s5')
03-19 01:49 root         INFO     DiskUtil.get_partition_info(dev='disk0s4', refresh_apfs=False)
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s4')
03-19 01:49 root         INFO     disk0s4 doesn't have any Volumes
03-19 01:49 root         INFO     DiskUtil.get_partition_info(dev='disk0s3', refresh_apfs=False)
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s3')
03-19 01:49 root         INFO     Checking #0 disk0s1...
03-19 01:49 root         INFO     Checking #1 disk0s2...
03-19 01:49 root         INFO     Checking #2 disk0s5...
03-19 01:49 root         INFO     Found previous partition disk0s5...
03-19 01:49 root         INFO     DiskUtil.get_partition_info(dev='disk0s4', refresh_apfs=True)
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk0s4')
03-19 01:49 root         INFO     DiskUtil.get_apfs_list()
03-19 01:49 root         DEBUG    get: diskutil ('apfs', 'list', 'disk5', '-plist')
03-19 01:49 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk5', '-plist')
03-19 01:49 root         INFO     New partition: Partition(name='disk0s4', offset=398531256320, size=2499805184, free=False, type='Apple_APFS', uuid='19356A93-A00C-4F5D-A41C-4FE2A1C2A7F4', desc=None, label='Asahi', info={'AESHardware': True, 'APFSContainerReference': 'disk5', 'Bootable': True, 'BusProtocol': 'Apple Fabric', 'CanBeMadeBootable': False, 'CanBeMadeBootableRequiresDestroy': False, 'Content': 'Apple_APFS', 'DeviceBlockSize': 4096, 'DeviceIdentifier': 'disk0s4', 'DeviceNode': '/dev/disk0s4', 'DeviceTreePath': 'IODeviceTree:/arm-io/ans@8F400000/iop-ans-nub/AppleANS3NVMeController', 'DiskUUID': '19356A93-A00C-4F5D-A41C-4FE2A1C2A7F4', 'Ejectable': False, 'EjectableMediaAutomaticUnderSoftwareControl': False, 'EjectableOnly': False, 'FreeSpace': 0, 'Fusion': False, 'GlobalPermissionsEnabled': False, 'IOKitSize': 2499805184, 'IORegistryEntryName': 'Untitled 4', 'Internal': True, 'MediaName': '', 'MediaType': 'Generic', 'MountPoint': '', 'OSInternalMedia': False, 'ParentWholeDisk': 'disk0', 'PartitionMapPartition': True, 'PartitionMapPartitionOffset': 398531256320, 'RAIDMaster': False, 'RAIDSlice': False, 'Removable': False, 'RemovableMedia': False, 'RemovableMediaOrExternalDevice': False, 'SMARTDeviceSpecificKeysMayVaryNotGuaranteed': {'AVAILABLE_SPARE': 100, 'AVAILABLE_SPARE_THRESHOLD': 99, 'CONTROLLER_BUSY_TIME_0': 0, 'CONTROLLER_BUSY_TIME_1': 0, 'DATA_UNITS_READ_0': 38060215, 'DATA_UNITS_READ_1': 0, 'DATA_UNITS_WRITTEN_0': 11237584, 'DATA_UNITS_WRITTEN_1': 0, 'HOST_READ_COMMANDS_0': 796665575, 'HOST_READ_COMMANDS_1': 0, 'HOST_WRITE_COMMANDS_0': 128955778, 'HOST_WRITE_COMMANDS_1': 0, 'MEDIA_ERRORS_0': 0, 'MEDIA_ERRORS_1': 0, 'NUM_ERROR_INFO_LOG_ENTRIES_0': 0, 'NUM_ERROR_INFO_LOG_ENTRIES_1': 0, 'PERCENTAGE_USED': 0, 'POWER_CYCLES_0': 149, 'POWER_CYCLES_1': 0, 'POWER_ON_HOURS_0': 168, 'POWER_ON_HOURS_1': 0, 'TEMPERATURE': 309, 'UNSAFE_SHUTDOWNS_0': 9, 'UNSAFE_SHUTDOWNS_1': 0}, 'SMARTStatus': 'Verified', 'Size': 2499805184, 'SolidState': True, 'SupportsGlobalPermissionsDisable': False, 'SystemImage': False, 'TotalSize': 2499805184, 'VolumeName': '', 'VolumeSize': 0, 'WholeDisk': False, 'Writable': True, 'WritableMedia': True, 'WritableVolume': False}, container={'APFSContainerUUID': '5A3FCC9D-09A1-4FBF-8E92-54EC8FEC4362', 'CapacityCeiling': 2499805184, 'CapacityFree': 2488877056, 'ContainerReference': 'disk5', 'DesignatedPhysicalStore': 'disk0s4', 'Fusion': False, 'PhysicalStores': [{'DeviceIdentifier': 'disk0s4', 'DiskUUID': '19356A93-A00C-4F5D-A41C-4FE2A1C2A7F4', 'Size': 2499805184}], 'Volumes': [{'APFSVolumeUUID': 'E7A9DCE9-AA28-47E0-86DA-83E01D528D47', 'CapacityInUse': 761856, 'CapacityQuota': 0, 'CapacityReserve': 0, 'CryptoMigrationOn': False, 'DeviceIdentifier': 'disk5s1', 'Encryption': True, 'FileVault': False, 'Locked': False, 'Name': 'Asahi', 'Roles': []}], 'VolumeGroups': []}, os=None)
03-19 01:49 root         INFO     MSG: Installing stub macOS into disk0s4 (Asahi)
03-19 01:49 root         INFO     StubInstaller.prepare_volume(part.name='disk0s4')
03-19 01:49 root         INFO     MSG: Preparing target volumes...
03-19 01:49 root         INFO      disk5s1 roles: ()
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'apfs', 'changeVolumeRole', 'disk5s1', 'D')
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'rename', 'disk5s1', 'Asahi - Data')
03-19 01:49 root         INFO     DiskUtil.refresh_part(part.name='disk0s4')
03-19 01:49 root         INFO     DiskUtil.get_apfs_list()
03-19 01:49 root         DEBUG    get: diskutil ('apfs', 'list', 'disk5', '-plist')
03-19 01:49 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk5', '-plist')
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'apfs', 'addVolume', 'disk5', 'apfs', 'Asahi', '-role', 'S', '-groupWith', 'disk5s1')
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'apfs', 'addVolume', 'disk5', 'apfs', 'Preboot', '-role', 'B')
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'apfs', 'addVolume', 'disk5', 'apfs', 'Recovery', '-role', 'R')
03-19 01:49 root         INFO     DiskUtil.refresh_part(part.name='disk0s4')
03-19 01:49 root         INFO     DiskUtil.get_apfs_list()
03-19 01:49 root         DEBUG    get: diskutil ('apfs', 'list', 'disk5', '-plist')
03-19 01:49 root         DEBUG    get: diskutil ('apfs', 'listVolumeGroups', 'disk5', '-plist')
03-19 01:49 root         INFO     StubInstaller.check_volume(self.part.name='disk0s4')
03-19 01:49 root         INFO     MSG: Checking volumes...
03-19 01:49 root         INFO     OSEnum.collect_part(part=disk0s4)
03-19 01:49 root         INFO     OSEnum.collect_os(part=disk0s4, vgid=E7A9DCE9-AA28-47E0-86DA-83E01D528D47)
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk5s3')
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk5s3')
03-19 01:49 root         INFO       mounts[Preboot]: /Volumes/Preboot 1
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk5s4')
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk5s4')
03-19 01:49 root         INFO       mounts[Recovery]: /Volumes/Recovery 2
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk5s2')
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk5s2')
03-19 01:49 root         INFO       mounts[System]: /Volumes/Asahi
03-19 01:49 root         DEBUG    run: diskutil ('quiet', 'mount', 'disk5s1')
03-19 01:49 root         DEBUG    get: diskutil ('info', '-plist', 'disk5s1')
03-19 01:49 root         INFO       mounts[Data]: /Volumes/Asahi - Data
03-19 01:49 root         INFO       Trying SystemVersion.plist...
03-19 01:49 root         INFO         Not Found
03-19 01:49 root         INFO       Trying SystemVersion-disabled.plist...
03-19 01:49 root         INFO         Not Found
03-19 01:49 root         WARNING    Failed to get AdminUserRecoveryInfo.plist
03-19 01:49 root         WARNING    bputil failed
03-19 01:49 root         INFO      Found [[1mAsahi[m] [1;31mincomplete install[m (macOS None stub) [disk5s2, E7A9DCE9-AA28-47E0-86DA-83E01D528D47]
03-19 01:49 root         INFO     StubInstaller.install_files()
03-19 01:49 root         INFO     VGID: E7A9DCE9-AA28-47E0-86DA-83E01D528D47
03-19 01:49 root         INFO     OS info: [[1mAsahi[m] [1;31mincomplete install[m (macOS None stub) [disk5s2, E7A9DCE9-AA28-47E0-86DA-83E01D528D47]
03-19 01:49 root         INFO     MSG: Beginning stub OS install...
03-19 01:49 root         INFO     Parsing metadata...
03-19 01:49 root         INFO     Using OS build 21E230 for j314sap
03-19 01:49 root         INFO     MSG: Setting up System volume...
03-19 01:49 root         INFO     Setting up System volume
03-19 01:49 root         INFO       usr/standalone/bootcaches.plist -> /Volumes/Asahi/
03-19 01:49 root         INFO       PlatformSupport.plist -> /Volumes/Asahi/System/Library/CoreServices/
03-19 01:49 root         INFO     xattr -wx com.apple.FinderInfo .... /Volumes/Asahi
03-19 01:49 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/stub.py", line 158, in install_files
    subprocess.run(["xattr", "-wx", "com.apple.FinderInfo",
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xattr', '-wx', 'com.apple.FinderInfo', '0000000000000000040000000000000000000000000000000000000000000000', '/Volumes/Asahi']' returned non-zero exit status 64.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 802, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 654, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 770, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 286, in action_install_into_free
    self.do_install(os_size)
  File "/private/tmp/asahi-install/main.py", line 293, in do_install
    self.ins.install_files(self.cur_os)
  File "/private/tmp/asahi-install/stub.py", line 162, in install_files
    p_err("Failed to apply extended attributes, logo will not work.")
NameError: name 'p_err' is not defined
03-19 01:49 root         INFO     MSG: If you need to file a bug report, please attach the log file:
03-19 01:49 root         INFO     MSG:   /private/tmp/asahi-install/installer.log

I do not have attr or other homebrew xattr alternatives that would break the installer. I could not figure out the cause of the error.

**Comment by georgeccotea** [comment]
I have found a (_jank_) fix. The xattr in the python framework `/Library/Frameworks/Python.framework/Versions/3.10/bin/xattr` was either out of date or broken. I overwrote this package with xattr from /usr/bin and the installation continued fine
