### ISSUE TITLE
[bug report] Downloading mozilla-openh264-2.4.1-2.fc40.aarch64.rpm aborted the installation

### ISSUE THREAD

**Issue by bxue** [AsahiLinux/asahi-installer#345]
Installing Asahi Linux by "curl https://alx.sh | sh" failed in the step where it was downloading mozilla-openh264-2.4.1-2.fc40.aarch64.rpm. I had set working proxies like:
```
% env | grep -i proxy
http_proxy=http://somedomain.com:3128
https_proxy=http://somedomain.com:3128
```
The distribution I chose was "Fedora KDE". I have tried the installation in the different date/time for several times in recent days, and it's 100% reproducible at my side. The installation log was like:
```
(...snapped...)
Downloading extra files...
  Downloading mozilla-openh264-2.4.1-2.fc40.aarch64.rpm (1/2)...
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1069, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 877, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1032, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 336, in action_install_into_free
    self.do_install(os_size)
  File "/private/tmp/asahi-install/main.py", line 456, in do_install
    self.osins.install(self.ins)
  File "/private/tmp/asahi-install/osinstall.py", line 173, in install
    self.download_extras()
  File "/private/tmp/asahi-install/osinstall.py", line 122, in download_extras
    ucache = urlcache.URLCache(url)
  File "/private/tmp/asahi-install/urlcache.py", line 26, in __init__
    self.size = self.get_size()
  File "/private/tmp/asahi-install/urlcache.py", line 83, in get_size
    con.request("HEAD", self.url.path, headers={"Connection":" keep-alive"})
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 928, in connect
    self._tunnel()
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 907, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 403 Forbidden
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
```
The installer.log is attached.
[installer.log](https://github.com/user-attachments/files/18062643/installer.log)

**Comment by bxue** [comment]
It turns out not a bug. After fixing my internet connection, the problem disappeared.

**Comment by Soupertonic** [comment]
Curious. I get the same exception and my internet works fine. 

```
Downloading extra files...
  Downloading mozilla-openh264-2.4.1-2.fc41.aarch64.rpm (1/2)...
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1069, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 877, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1032, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 336, in action_install_into_free
    self.do_install(os_size)
  File "/private/tmp/asahi-install/main.py", line 456, in do_install
    self.osins.install(self.ins)
  File "/private/tmp/asahi-install/osinstall.py", line 173, in install
    self.download_extras()
  File "/private/tmp/asahi-install/osinstall.py", line 123, in download_extras
    data = ucache.read()
  File "/private/tmp/asahi-install/urlcache.py", line 200, in read
    d[0] = d[0][trim:]
IndexError: list index out of range
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
```

**Comment by cublae** [comment]
the same error

**Comment by Soupertonic** [comment]
Am I doing something wrong or is this an actual bug?
