### ISSUE TITLE
Better error message running on an x86 mac

### ISSUE THREAD

**Issue by Gaelan** [AsahiLinux/asahi-installer#37]
This is a pretty silly thing to try! But someone will probably expect it to work, so a nice error message would be a good idea.

```
$ uname -m
x86_64
$ curl https://alx.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   967  100   967    0     0   4405      0 --:--:-- --:--:-- --:--:--  4649

Bootstrapping installer:
  Checking version...
  Version: v0.3.5
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
Password:

Welcome to the Asahi Linux installer!

This installer is in an alpha state, and may not work for everyone.
It is intended for developers and early adopters who are comfortable
debugging issues or providing detailed bug reports.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.


By default, this installer will hide certain advanced options that
are only useful for developers. You can enable expert mode to show them.
» Enable expert mode? (y/N): n

Collecting system information...
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 803, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 624, in main
    self.sysinfo = system.SystemInfo()
  File "/private/tmp/asahi-install/system.py", line 8, in __init__
    self.fetch()
  File "/private/tmp/asahi-install/system.py", line 24, in fetch
    self.product = product = self.get_child(dt, "product")
  File "/private/tmp/asahi-install/system.py", line 128, in get_child
    raise Exception(f"Could not find {name}")
Exception: Could not find product
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
```

**Comment by marcan** [comment]
Good idea! Fixed in bc29c7bce :)
