### ISSUE TITLE
Detect the high tidemark of the macOS volume

### ISSUE THREAD

**Issue by j-f1** [AsahiLinux/asahi-installer#39]
My install process is failing, probably because of local Time Machine snapshots. It would be awesome if the installer looked up and preemptively displayed the “APFS-system-imposed minimal container size.” Additionally, it would be nice to have an early exit with a clear error message if it isn’t possible to create a sufficiently-sized volume on the remaining available disk space.

```
Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (994.66 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v12.3 [disk3s1, 0F0DA22A-19C6-4FC9-887E-9942D12D0932]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.3 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): 


We're going to resize this partition:
  APFS [Macintosh HD] (994.66 GB, 6 volumes)
  Total size: 994.66 GB
  Free space: 55.21 GB
  Minimum free space: 38.00 GB
  Minimum total size: 977.45 GB (98.27%)

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (min): 978GB            

Resizing will free up 16.66 GB of space.
» Continue? (y/N): y

Started APFS operation
Aligning shrink delta to 16,663,089,152 bytes and targeting a new physical store size of 977,999,495,168 bytes
Determined the minimum size for the targeted physical store of this APFS Container to be 994,662,584,320 bytes
Error: -69521: Your APFS Container resize request is below the APFS-system-imposed minimal container size (perhaps caused by APFS Snapshot usage by Time Machine)
Failed to run process: diskutil apfs resizeContainer disk0s2 977999495168
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 803, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 655, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 775, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 595, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 191, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 37, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '977999495168']' returned non-zero exit status 1.
```

**Comment by IonCannon218** [comment]
Yes, having a precheck for the minimal AFPS size would help, I had to run the script multiple times before I realized I can't even shrink the volume even after removing local Time Machine snapshots. I tried down to 10GB and it still wouldn't work.

```
Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (245.11 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v12.3 [disk3s1, ]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.3 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): r


We're going to resize this partition:
  APFS [Macintosh HD] (245.11 GB, 6 volumes)
  Total size: 245.11 GB
  Free space: 152.93 GB
  Minimum free space: 38.00 GB
  Minimum total size: 130.18 GB (53.11%)

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (min): 235GB

Resizing will free up 10.11 GB of space.

Note: your system may appear to freeze during the resize.
This is normal, just wait until the process completes.
» Continue? (y/N): y

Started APFS operation
Aligning shrink delta to 10,107,682,816 bytes and targeting a new physical store size of 234,999,513,088 bytes
Determined the minimum size for the targeted physical store of this APFS Container to be 245,107,195,904 bytes
Error: -69521: Your APFS Container resize request is below the APFS-system-imposed minimal container size (perhaps caused by APFS Snapshot usage by Time Machine)
Failed to run process: diskutil apfs resizeContainer disk0s2 234999513088
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 807, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 659, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 779, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 599, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 202, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '234999513088']' returned non-zero exit status 1.```

**Comment by marcan** [comment]
This is now fixed (in dev builds, not released yet).
