### ISSUE TITLE
TypeError exception when installing UEFI only environment

### ISSUE THREAD

**Issue by kyelewis** [AsahiLinux/asahi-installer#40]
After following the install process, with a 300/700GB split, on the "Install an OS into free space - Creating new stub macOS" step when selecting UEFI only flow, I get the following error.

```
Creating new stub macOS named NixOS
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 806, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 658, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 774, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 286, in action_install_into_free
    self.do_install(os_size - STUB_SIZE)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/8310123/installer.log)

MacBook Pro 13" M1 2020,  MacoS 12.3 (21E230)

This also leaves the partitions created in place, creating a new one every attempt

**Comment by kyelewis** [comment]
Thanks, confirmed this change works and all is working well.
