### ISSUE TITLE
Installer fails at resizing disk

### ISSUE THREAD

**Issue by Knallli** [AsahiLinux/asahi-installer#43]
Installer fails with the following error:

> Shrinking APFS data structures 
APFS Container Resize error code is 49187 
Error: -69606: A problem occurred while resizing APFS Container structures 
Failed to run process: diskutil apfs resizeContainer disk0s2 213021360128 
root        : ERROR    Process execution failed 
Traceback (most recent call last): 
  File "/private/tmp/asahi-install/main.py", line 807, in <module> 
    InstallerMain().main() 
  File "/private/tmp/asahi-install/main.py", line 659, in main 
    while self.main_loop(): 
  File "/private/tmp/asahi-install/main.py", line 779, in main_loop 
    return self.action_resize(parts_resizable) 
  File "/private/tmp/asahi-install/main.py", line 599, in action_resize 
    self.dutil.resizeContainer(target.name, val) 
  File "/private/tmp/asahi-install/diskutil.py", line 191, in resizeContainer 
    self.action("apfs", "resizeContainer", name, size, verbose=2) 
  File "/private/tmp/asahi-install/diskutil.py", line 37, in action 
    subprocess.run(["diskutil"] + list(args), check=True) 
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run 
    raise CalledProcessError(retcode, process.args, 
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '213021360128']' returned non-zero exit status 1. 

Log is attached below.

[iTerm2 Session 20. Mar 2022 at 12:12:30 PM.txt](https://github.com/AsahiLinux/asahi-installer/files/8311101/iTerm2.Session.20.Mar.2022.at.12.12.30.PM.txt)

**Comment by Knallli** [comment]
https://github.com/AsahiLinux/docs/issues/12#issuecomment-1073013711

This procedure seemed to have fixed it
