### ISSUE TITLE
checksums for large files

### ISSUE THREAD

**Issue by moham96** [AsahiLinux/asahi-installer#52]
Hello
The CDN should host checksum files for large files such as the os images and the installer should check against these checksums before trying to unpack the archives, it happened to me one time where the download was corrupted along the way and caused this exception:

 ```
 Extracting root.img into disk0s5 partition...
    6.92% root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/Users/rhx/asahi/asahi-install/main.py", line 807, in <module>
    InstallerMain().main()
  File "/Users/rhx/asahi/asahi-install/main.py", line 659, in main
    while self.main_loop():
  File "/Users/rhx/asahi/asahi-install/main.py", line 775, in main_loop
    return self.action_install_into_free(parts_free)
  File "/Users/rhx/asahi/asahi-install/main.py", line 287, in action_install_into_free
    self.do_install(os_size)
  File "/Users/rhx/asahi/asahi-install/main.py", line 305, in do_install
    self.osins.install(self.ins.boot_obj_path)
  File "/Users/rhx/asahi/asahi-install/osinstall.py", line 110, in install
    self.fdcopy(sfd, dfd, zinfo.file_size)
  File "/Users/rhx/asahi/asahi-install/util.py", line 144, in fdcopy
    d = sfd.read(BLOCK)
  File "/Users/rhx/asahi/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 922, in read
    data = self._read1(n)
  File "/Users/rhx/asahi/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 998, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code lengths set
```

Regards

**Comment by marcan** [comment]
ZIP files already have checksums, so this is implied. The question is why the download was unreliable here. Was it a CDN problem? It's HTTPS, so it can't be the network in between. If it's a CDN problem we need to isolate it and report it to bunny.net...
