### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by KingBBQ** [AsahiLinux/asahi-installer#53]
At the end of the installation, "Preparing to finish installation..." the script stops directly after entering the sudo password...

`03-21 19:09 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 807, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 659, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 775, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 287, in action_install_into_free
    self.do_install(os_size)
  File "/private/tmp/asahi-install/main.py", line 311, in do_install
    self.step2()
  File "/private/tmp/asahi-install/main.py", line 401, in step2
    self.startup_disk()
  File "/private/tmp/asahi-install/main.py", line 467, in startup_disk
    return self.bless()
  File "/private/tmp/asahi-install/main.py", line 371, in bless
    self.get_admin_credentials()
  File "/private/tmp/asahi-install/main.py", line 191, in get_admin_credentials
    self.admin_password = getpass.getpass(f'Password for {self.admin_user}: ')
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass
    passwd = _raw_input(prompt, stream, input=input)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input
    line = input.readline()
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
03-21 19:09 root         INFO     MSG: If you need to file a bug report, please attach the log file:
03-21 19:09 root         INFO     MSG:   /private/tmp/asahi-install/installer.log
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/8318249/installer.log)
`

**Comment by KingBBQ** [comment]
Actually yes. That's also what I suspected. Just changed my pw to test it.

**Comment by marcan** [comment]
Should be fixed now in v0.3.18!

**Comment by KingBBQ** [comment]
Testes again, now it works also with the strange German characters ;-) thanks.
