### ISSUE TITLE
Resize APFS error

### ISSUE THREAD

**Issue by leomiglio02** [AsahiLinux/asahi-installer#54]
MACOS 12.3
MacBook Pro with m1 pro
`The container /dev/disk0s2 could not be verified completely
Storage system check exit code is 8
Error: -69716: Storage system verify or repair failed
Failed to run process: diskutil apfs resizeContainer disk0s2 469999026176
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 807, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 659, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 779, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 599, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 202, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '469999026176']' returned non-zero exit status 1.
`
I also received this error before `error: doc-id tree: record exists for doc-id 19220, file-id 5292977 but no inode references this doc-id
`

**Comment by leomiglio02** [comment]
This is more readable
`Error: -69716: Storage system verify or repair failed
Failed to run process: diskutil apfs resizeContainer disk0s2 469999026176
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 807, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 659, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 779, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 599, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 202, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '469999026176']' returned non-zero exit status 1.`

**Comment by leomiglio02** [comment]
It seems that the first aid from booted system have the same effect and resolve the issue
