### ISSUE TITLE
Storage System Verify or Repair Failed

### ISSUE THREAD

**Issue by maximalisms** [AsahiLinux/asahi-installer#88]
Getting this return after setting the parameters for the partition resize:

Running MacBook Air M1 2020

```
error: doc-id tree: record exists for doc-id 64, file-id 9665861 but no inode references this doc-id
Checking the extent ref tree
Checking the file key rolling tree
Verifying volume object map space
The volume /dev/rdisk3s5 was found to be corrupt and needs to be repaired
Checking volume /dev/rdisk3s6
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s6 appears to be OK
Verifying allocated space
Performing deferred repairs
error: doc-id tree record exists f

The container /dev/disk0s2 could not be verified completely
Storage system check exit code is 8
Error: -69716: Storage system verify or repair failed
Failed to run process: {cmd}
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 802, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 654, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 774, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 594, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 191, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 37, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '116980187136']' returned non-zero exit status 1.
```

Dont really contribute much, so if there are details you guys must know please let me know so I can fill out more accurate bug reports.

**Comment by marcan** [comment]
Duplicate of #81
